tasks:
  - id: install-dependencies
    name: Install dependencies
    command: pip install -r requirements.txt

  - id: open-notebook
    name: Open Jupyter Notebook
    command: gp open quickstart-demo.ipynb
    dependsOn: [install-dependencies]

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags