image: gitpod/workspace-full
tasks:
  - name: startup
    init: pip install -r requirements.txt
    command: gp open quickstart-demo.ipynb


vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-python.debugpy
    - ms-toolsai.vscode-jupyter-slideshow
